language: objective-c
osx_image: xcode7.2
xcode_project: KeenClient.xcodeproj
xcode_scheme: KeenClient
xcode_sdk: iphonesimulator9.2
before_install:
  - gem install bundler
  - bundle --version
  - rvm use $RVM_RUBY_VERSION
install: bundle install --without=documentation --path ../travis_bundle_dir
after_success: slather